In [54]:
import pandas as pd
import numpy as np

# create variables for scoring settings
global pointsScored, totalRebounds, assists, steals, blockedShots, turnovers
pointsScored = 1.0
totalRebounds = 1.2
assists = 1.5
steals = 3.0
blockedShots = 3.0
turnovers = -1.0

In [55]:
# load Master_topPicks into dataframe
df = pd.read_csv("topPicksCSV/Playoffs-Master_topPicks.csv")

# keep only the columns we need
stats_to_keep = [
    "Player",
    "Pos",
    "Tm",
    "G",
    "MP",
    "TRB",
    "AST",
    "STL",
    "BLK",
    "TOV",
    "PTS",
    "Year",
]
df = df[stats_to_keep]

# capture each player occurences
# df = df.groupby(["Player"]).sum().reset_index()

# if a player has played for multiple years, average their stats across those years
numeric_cols = df.select_dtypes(include=["float64", "int64"]).columns
df = df.groupby(["Player"])[numeric_cols].mean().reset_index()

# drop year column
df = df.drop("Year", axis=1)

In [56]:
# create calculated column for fantasy points
df["FantasyPoints"] = (
    df["PTS"] * pointsScored
    + df["TRB"] * totalRebounds
    + df["AST"] * assists
    + df["STL"] * steals
    + df["BLK"] * blockedShots
    + df["TOV"] * turnovers)

#round to the nearest decimal
df = df.round(1)

In [57]:
# write to csv
df.to_csv("topPicksCSV/Playoffs-Master-Combined_topPicks.csv", index=False)

df

              Player     G    MP  TRB  AST  STL  BLK  TOV   PTS  FantasyPoints
0       Aaron Gordon  11.7  32.5  6.2  2.4  0.5  0.7  1.3  12.7           26.1
1      Aaron Holiday   3.7   8.4  0.6  1.7  0.5  0.1  0.7   3.8            8.0
2      Aaron Nesmith  10.0   9.2  1.8  0.2  0.2  0.2  0.2   2.0            5.4
3        Abdel Nader   4.0   7.0  1.0  0.0  0.2  0.4  0.0   1.0            3.8
4         Al Horford  15.7  32.9  7.9  2.9  0.7  1.4  0.9   8.6           28.0
..               ...   ...   ...  ...  ...  ...  ...  ...   ...            ...
455     Yogi Ferrell   9.0   1.7  0.3  0.3  0.0  0.0  0.0   0.4            1.2
456    Yuta Watanabe   2.5   3.8  0.5  0.0  0.0  0.0  0.6   2.0            2.0
457      Zach LaVine   4.0  38.3  5.3  6.0  0.8  0.3  3.0  19.3           35.0
458       Zeke Nnaji   4.0   3.5  0.3  0.1  0.1  0.0  0.1   1.6            2.5
459  Ziaire Williams   7.0   9.9  1.0  0.5  0.2  0.0  0.4   4.1            6.5

[460 rows x 10 columns]